"""empty message

Revision ID: c2b05622709f
Revises: 
Create Date: 2024-05-03 11:26:48.698352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b05622709f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('adventures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('adventureDate', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creatorId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId1', sa.Integer(), nullable=False),
    sa.Column('userId2', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('request_userId1', 'request_userId2', 'friend'), nullable=False),
    sa.CheckConstraint('userId1 < userId2'),
    sa.ForeignKeyConstraint(['userId1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('instructionTypeId', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creatorId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instructionTypeId'], ['instruction_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adventure_instruction',
    sa.Column('adventureId', sa.Integer(), nullable=False),
    sa.Column('instructionId', sa.Integer(), nullable=False),
    sa.Column('isUsed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['adventureId'], ['adventures.id'], ),
    sa.ForeignKeyConstraint(['instructionId'], ['instructions.id'], ),
    sa.PrimaryKeyConstraint('adventureId', 'instructionId')
    )
    op.create_table('adventure_membership',
    sa.Column('adventureId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'pending', 'declined'), nullable=False),
    sa.ForeignKeyConstraint(['adventureId'], ['adventures.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('adventureId', 'userId')
    )
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adventureId', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('isCover', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adventureId'], ['adventures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    op.drop_table('adventure_membership')
    op.drop_table('adventure_instruction')
    op.drop_table('instructions')
    op.drop_table('friends')
    op.drop_table('adventures')
    op.drop_table('users')
    op.drop_table('instruction_types')
    # ### end Alembic commands ###